#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer Cor { vec2 data[]; } corr;
layout(std430, binding = 1) readonly buffer BCo { float data[]; } bcorr;
layout(std430, binding = 2) readonly buffer UV  { vec2 data[]; } uv;
layout(std430, binding = 3) buffer Cl { vec4 data[]; } correl;
layout(push_constant) uniform PC { int width; int height; } pc;
void main() {
  int col = int(gl_GlobalInvocationID.x);
  int row = int(gl_GlobalInvocationID.y);
  if(col >= pc.width || row >= pc.height) return;
  int k = row * pc.width + col;
  correl.data[k].x = uv.data[k].x * corr.data[k].y;
  correl.data[k].y = uv.data[k].y * corr.data[k].y;
  correl.data[k].z = uv.data[k].x * bcorr.data[k];
  correl.data[k].w = uv.data[k].y * bcorr.data[k];
}
