#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer In  { vec4 data[]; } in_buf;
layout(std430, binding = 1)          buffer Out { vec4 data[]; } out_buf;
layout(push_constant) uniform PC {
  int width; int height; int pixel_radius;
} pc;

void main() {
  int i = int(gl_GlobalInvocationID.x);
  int j = int(gl_GlobalInvocationID.y);
  int pr2 = 2 * pc.pixel_radius;
  int pixels_x = pc.width  / pr2;
  int pixels_y = pc.height / pr2;
  if(i > pixels_x || j > pixels_y) return;

  int tlx = clamp(pr2 * i,                  0, pc.width  - 1);
  int tly = clamp(pr2 * j,                  0, pc.height - 1);
  int ccx = clamp(tlx + pc.pixel_radius,    0, pc.width  - 1);
  int ccy = clamp(tly + pc.pixel_radius,    0, pc.height - 1);
  int brx = clamp(ccx + pc.pixel_radius,    0, pc.width  - 1);
  int bry = clamp(ccy + pc.pixel_radius,    0, pc.height - 1);

  vec4 rgb = vec4(0.0);
  rgb += in_buf.data[tly * pc.width + tlx] / 5.0;
  rgb += in_buf.data[tly * pc.width + brx] / 5.0;
  rgb += in_buf.data[ccy * pc.width + ccx] / 5.0;
  rgb += in_buf.data[bry * pc.width + tlx] / 5.0;
  rgb += in_buf.data[bry * pc.width + brx] / 5.0;

  for(int jj = tly; jj < bry; jj++)
    for(int ii = tlx; ii < brx; ii++)
      out_buf.data[jj * pc.width + ii] = rgb;
}
