#version 450
#define HISTN 2048
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly  buffer In   { vec4  data[]; } in_buf;
layout(std430, binding = 1)           buffer Out  { vec4  data[]; } out_buf;
layout(std430, binding = 2) readonly  buffer Hist { int   data[]; } target_hist;
layout(std430, binding = 3) readonly  buffer IHst { float data[]; } source_ihist;
layout(push_constant) uniform PC {
  int width; int height; float equalization;
} pc;

void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.width || y >= pc.height) return;

  int idx = y * pc.width + x;
  float L = in_buf.data[idx].x;

  int bin = int(clamp(float(HISTN) * L / 100.0, 0.0, float(HISTN - 1)));
  float dL = 0.5 * ((L * (1.0 - pc.equalization)
                     + source_ihist.data[target_hist.data[bin]] * pc.equalization) - L)
             + 50.0;
  dL = clamp(dL, 0.0, 100.0);

  out_buf.data[idx] = vec4(dL, 0.0, 0.0, 0.0);
}
