#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly  buffer BL { vec4 data[]; } bl_buf;
layout(std430, binding = 1)           buffer BH { vec4 data[]; } bh_buf;
layout(push_constant) uniform PC { int width; int height; } pc;

void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.width || y >= pc.height) return;
  int idx = y * pc.width + x;
  bh_buf.data[idx] -= bl_buf.data[idx];
}
