#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer In  { vec4 data[]; } in_buf;
layout(std430, binding = 1)          buffer Out { vec4 data[]; } out_buf;
layout(push_constant) uniform PC {
  int owidth; int oheight; int iwidth; int iheight; int dx; int dy;
} pc;

void main() {
  int ocol = int(gl_GlobalInvocationID.x);
  int orow = int(gl_GlobalInvocationID.y);
  if(ocol >= pc.owidth || orow >= pc.oheight) return;

  vec4 pix = vec4(0.0);
  int irow = orow + pc.dy;
  int icol = ocol + pc.dx;
  if(irow >= 0 && irow < pc.iheight && icol >= 0 && icol < pc.iwidth)
    pix = in_buf.data[irow * pc.iwidth + icol];

  out_buf.data[orow * pc.owidth + ocol] = pix;
}
