#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly  buffer In  { vec4  data[]; } in_buf;
layout(std430, binding = 1)           buffer Pad { float data[]; } padded;
layout(push_constant) uniform PC {
  int wd; int ht; int max_supp; int wd2; int ht2;
} pc;

void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.wd2 || y >= pc.ht2) return;
  int cx = clamp(x - pc.max_supp, 0, pc.wd - 1);
  int cy = clamp(y - pc.max_supp, 0, pc.ht - 1);
  padded.data[y * pc.wd2 + x] = in_buf.data[cy * pc.wd + cx].x * 0.01;
}
