#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer In    { vec4 data[]; } in_buf;
layout(std430, binding = 1)          buffer Out   { vec4 data[]; } out_buf;
layout(std430, binding = 2) readonly buffer Co    { float data[]; } coord_buf;
layout(std430, binding = 3) readonly buffer Raw   { uint data[]; } raw_buf;
layout(std430, binding = 4) readonly buffer Xtr   { uint data[]; } xtrans_buf;
layout(push_constant) uniform PC {
  int width; int height; int raw_width; int raw_height;
  uint filters;
  uint thr0; uint thr1; uint thr2; uint thr3;
} pc;

int vk_FC(int row, int col, uint filters) {
  return int((filters >> uint((((row << 1) & 14) + (col & 1)) << 1)) & 3u);
}
int vk_FCxtrans(int row, int col) {
  return int(xtrans_buf.data[((row + 600) % 6) * 6 + ((col + 600) % 6)]);
}

void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.width || y >= pc.height) return;

  int piwidth = 2 * pc.width;
  int ci = y * piwidth + 2 * x;
  int raw_x = int(coord_buf.data[ci]);
  int raw_y = int(coord_buf.data[ci + 1]);

  if(raw_x < 0 || raw_y < 0 || raw_x >= pc.raw_width || raw_y >= pc.raw_height)
    return;

  uint raw_pixel = raw_buf.data[raw_y * pc.raw_width + raw_x];
  int c = (pc.filters == 9u) ? vk_FCxtrans(raw_y, raw_x) : vk_FC(raw_y, raw_x, pc.filters);

  uint thr = (c == 0) ? pc.thr0 : ((c == 1) ? pc.thr1 : ((c == 2) ? pc.thr2 : pc.thr3));
  if(raw_pixel < thr) return;

  vec4 pixel = max(vec4(0.0), in_buf.data[y * pc.width + x]);
  if(c == 2)      pixel.z = 0.0;
  else if(c == 1) pixel.y = 0.0;
  else if(c == 0) pixel.x = 0.0;

  out_buf.data[y * pc.width + x] = pixel;
}
