#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) buffer In { vec4 data[]; } in_buf;
layout(push_constant) uniform PC { int width; int height; } pc;
void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.width || y >= pc.height) return;
  vec4 p = in_buf.data[y * pc.width + x];
  p.w = 0.0;
  in_buf.data[y * pc.width + x] = p;
}
