#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(std430, binding = 0) readonly buffer In  { vec4 data[]; } in_buf;
layout(std430, binding = 1)          buffer Out { vec4 data[]; } out_buf;
layout(push_constant) uniform PC {
  int in_width; int in_height;
  int out_width; int out_height;
  int xoffs; int yoffs;
} pc;
void main() {
  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);
  if(x >= pc.out_width || y >= pc.out_height) return;
  if(x + pc.xoffs >= pc.in_width || y + pc.yoffs >= pc.in_height) return;
  out_buf.data[y * pc.out_width + x] =
      in_buf.data[(y + pc.yoffs) * pc.in_width + (x + pc.xoffs)];
}
